/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.generica.epos.dbpatcher.gui;

import fa.gs.result.simple.Result;
import fa.gs.result.simple.Results;
import py.com.generica.epos.dbpatcher.db.DatabaseClient;
import py.com.generica.epos.dbpatcher.db.Tables;
import py.com.generica.epos.dbpatcher.gui.utils.Async;
import py.com.generica.epos.dbpatcher.gui.utils.Widgets;

/**
 *
 * @author Fabio A. González Sosa
 */
public class Verifier extends javax.swing.JFrame {

    /**
     * Cliente de base de datos.
     */
    private final DatabaseClient client;

    /**
     * Creates new form Verifier
     *
     * @param client Cliente de base de datos.
     */
    public Verifier(DatabaseClient client) {
        initComponents();
        this.client = client;

        // Iniciar proceso de verificacion.
        Async.run(new Async.Runner<Void>() {
            @Override
            public Void run() throws Throwable {
                verificar();
                return null;
            }
        });
    }

    private void setPrimaryText(String fmt, Object... args) {
        Widgets.text(lblPrimary, fmt, args);
    }

    private void setSecondaryText(String fmt, Object... args) {
        Widgets.text(lblSecondary, fmt, args);
    }

    private void verificar() {
        setPrimaryText("Verificando");
        setSecondaryText("Tabla '%s'", Tables.TABLE_PARCHES);
        Result<Boolean> res1 = tablaParchesExiste();
        boolean tablaExiste = res1.value(Boolean.FALSE);

        setPrimaryText("Listo");
        setSecondaryText("");
    }

    private Result<Boolean> tablaParchesExiste() {
        Result<Boolean> result;

        try {
            boolean exists = client.tableExists(Tables.TABLE_PARCHES);

            result = Results.ok()
                    .value(exists)
                    .build();
        } catch (Throwable thr) {
            result = Results.ko()
                    .message("Ocurrió un problema verificando tabla '%s'", Tables.TABLE_PARCHES)
                    .cause(thr)
                    .build();
        }

        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbProgreso = new javax.swing.JProgressBar();
        lblPrimary = new javax.swing.JLabel();
        lblSecondary = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblPrimary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrimary.setText("Espere por favor");

        lblSecondary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSecondary.setText("Iniciando ...");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(lblPrimary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecondary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pbProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrimary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSecondary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPrimary;
    private javax.swing.JLabel lblSecondary;
    private javax.swing.JProgressBar pbProgreso;
    // End of variables declaration//GEN-END:variables
}
